# 以UTF-8 编码格式进行保存
spring: 
  profiles: 
    active: 
    - dev
    
---

spring: 
  profiles: dev  # 开发环境
  applition: 
    name: config-server-dev
    
---

spring: 
  profiles: test
  applition: 
    name: config-server-test  # 测试环境