# 以UTF-8 编码格式进行保存
spring: 
  profiles: 
    active: 
    - dev
    
---

server: 
  port: 8201
spring: 
    profiles: dev
    applition: config-client
eureka: # 绑定服务端的地址
 client: 
  service-url: 
   defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/,http://eureka-server-7003:7003/eureka/
 instance: # 设置当前服务在 Eureka 注册中心显示的ID名称
    instance-id: config-client
    prefer-ip-address: true # 以IP地址形式注册该服务
    
---

server: 
  port: 8202
spring: 
    profiles: test
    applition: config-client
eureka: # 绑定服务端的地址
 client: 
  service-url: 
   defaultZone: http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/,http://eureka-server-7003:7003/eureka/
 instance: # 设置当前服务在 Eureka 注册中心显示的ID名称
    instance-id: config-client
    prefer-ip-address: true # 以IP地址形式注册该服务