spring: 
  profiles: 
    active: 
    - dev
    
---

server: 
  port: 7001
  
spring: 
  profiles: dev
  application: 
    name: config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka-server-7001
  client: 
    register-with-rureka: false
    fetch-registry: false
    service-url: 
     defaultZone: http://eureka-server-7001:7001/eureka/

---

server: 
  port: 7002
  
spring: 
  profiles: test
  application: 
    name: config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka-server-7002
  client: 
    register-with-rureka: false
    fetch-registry: false
    service-url: 
     defaultZone: http://eureka-server-7002:7002/eureka/