spring: 
  profiles: 
    active: 
    - dev
    
---

server: 
  port: 8001
  
spring: 
  profiles: dev
  application: 
    name: provider-client
  datasource:
      # 当前数据源操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      # mysql驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库名称
      url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      #url: jdbc:mysql://192.168.58.128:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.cnm.entity
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml
    
eureka: 
  client: 
    service-url: 
     defaultZone: http://eureka-server-7001:7001/eureka/
  instance: 
    instance-id: provider-8001
    prefer-ip-address: true # 以IP地址形式注册该服务
    
info: 
  app.name: Spring-Cloud-Demo
  company.name: www.shabi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server: 
  port: 8002
  
spring: 
  profiles: test
  application: 
    name: provider-client
  datasource:
      # 当前数据源操作类型
      type: com.alibaba.druid.pool.DruidDataSource
      # mysql驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库名称
      url: jdbc:mysql://localhost:3306/cloudDB02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      #url: jdbc:mysql://192.168.58.128:3306/cloudDB02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      dbcp2:
         min-idle: 5 # 数据库连接池的最小维持连接数
         initial-size: 5 # 初始化连接数
         max-total: 5 # 最大连接数
         max-wait-millis: 200 # 等待连接获取的最大超时时间
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.cnm.entity
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml
    
eureka: 
  client: 
    service-url: 
     defaultZone: http://eureka-server-7002:7002/eureka/
  instance: 
    instance-id: provider-8002
    prefer-ip-address: true # 以IP地址形式注册该服务
    
info: 
  app.name: Spring-Cloud-Demo
  company.name: www.shabi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$